config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # root 'home#index'
  root 'friends#index'
  get 'home/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    
    @q = Friend.ransack(params[:q])
    @friends = @q.result
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build()
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorised To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  def about
    @about_me = "A friends list app to help learn Ruby on Rails by Mark Johnston"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control my-2",
    placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control my-2",
    placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control my-2",
    placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control my-2",
    placeholder:"Phone" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter, class:"form-control my-2",
    placeholder:"Twitter" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id,
    class:"form-control my-2", value:current_user.id,
    type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend, class:"btn btn-secondary my-2" %>
<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<%= link_to 'Back', friends_path, class:"btn btn-secondary my-2" %>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<h1>Friends</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
      <tr>
        <td><%= link_to friend.first_name + " " + friend.last_name, friend %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>
<% else %>
<h1 class="mb-3">Welcome to Friends</h1>
<h2 class="mb-5">Keep all your friends details in one handy place!</h2>
<%= link_to 'Sign In', new_user_session_path, class:"btn btn-secondary" %>
<%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-secondary" %>
<% end %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class:"btn btn-secondary my-2" %>

app/views/friends/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"><%= @friend.first_name %> <%= @friend.last_name %></h1>
    <p class="col-md-8 fs-4 pb-4"><%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %></p>
    <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary my-2" %>
    <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    <%= link_to 'Back', friends_path, class:"btn btn-secondary my-2" %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
  <div class="container-fluid">
  	<%= link_to 'Friends', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class: "nav-link" %>
        </li>		
		<% if user_signed_in? %>
			<li class="nav-item">
			<%= link_to 'Add Friend', new_friend_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
			<%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
			<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
			</li>
		<% else %>
			<li class="nav-item">
			<%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
			<%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
			</li>
		<% end %>
      </ul>
	  	<% if user_signed_in? %>
			<form class="d-flex" >
				<% if @q %>
					<%= search_form_for @q do |f| %>
					<%= f.search_field :first_name_cont, class:"form-control me-2" %>
					<%= f.submit class:"btn btn-outline-success" %>
					<% end %>
				<% end %>
			</form>
		<% end %>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About...</h1>

<p>
	<%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
<h2> This is my first page in Rails </h2>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Friends App</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
        <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>